spring:
  kafka:
    consumer:
      bootstrap-servers: b-1.democluster1.ya11o8.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-3.democluster1.ya11o8.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-2.democluster1.ya11o8.c2.kafka.ap-northeast-2.amazonaws.com:9092
      group-id: foo
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      bootstrap-servers: b-1.democluster1.ya11o8.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-3.democluster1.ya11o8.c2.kafka.ap-northeast-2.amazonaws.com:9092,b-2.democluster1.ya11o8.c2.kafka.ap-northeast-2.amazonaws.com:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer